name: Azure Resource Deployment

on:
  push:
    branches:
      - main  # Trigger deployment on push to the 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy Resources
      run: |
        # Example: Deploy a resource group (You can replace it with your own resource deployment script)
        az group create --name MyResourceGroup --location eastus
        az storage account create --name mystorageaccount --resource-group MyResourceGroup --location eastus --sku Standard_LRS
